---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.8"}

inputs:
- name: gp-version
- name: git-phlow

outputs:
- name: build-artifacts

run:
  path: git-phlow/ci/scripts/build.sh
